# Generated by Django 4.1.2 on 2022-10-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
