# Generated by Django 4.1.2 on 2022-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateField(auto_now_add=True),
        ),
    ]
