# Generated by Django 4.1.2 on 2022-10-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_comment_date_commented'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
